### ISSUE TITLE
Incorrect service name in Fault injection snippet

### ISSUE THREAD

**Issue by drrk** [kong-education/kong-mesh-ops#2]
https://github.com/kong-education/kong-mesh-ops/blob/02821c69319b78967abddaa83d394b1d6f767082/04/abortFaultInjection.yaml#L9
https://github.com/kong-education/kong-mesh-ops/blob/02821c69319b78967abddaa83d394b1d6f767082/04/abortFaultInjection.yaml#L13

Both refer to kuma-demo not kong-mesh demo and therefore don't work correctly.

**Comment by rexcatus** [comment]
Same thing applicable to delayFaultInjection.yaml and bandwidthFaultInjection.yaml.

**Comment by rexcatus** [comment]
service names fixed.
